<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript">
//<![CDATA[
     var jQuery= jQuery.noConflict();
//]]>
</script>
<?php echo $this->getCssJsHtml() ?>
	<div class="container-fluid"><div id="PPLSAYContainer" class="row">
			<script type="text/javascript">
					//uploading ppls js and css
				var ppls_cdn_url = "<?php echo $this->getPPLSayCdnURL();?>";
				var productName =  "<?php echo $this->getProductName();?>";
				var productID = "<?php echo $this->getProductId();?>";
				var baseUrl = "<?php echo Mage::getBaseUrl(); ?>";
				var pplsCSS=document.createElement('link');
				var headElem = document.getElementsByTagName("head")[0];
				var packageName = "<?php echo Mage::getSingleton('core/design_package')->getPackageName();?>";
				var themeName = "<?php echo Mage::getSingleton('core/design_package')->getTheme('frontend');?>";
				var lang = "<?php echo Mage::app()->getLocale()->getLocaleCode();?>";
				var pplsVer = "<?php echo Mage::getConfig()->getNode()->modules->PPLS_Discussions->version;?>";
     				pplsCSS.setAttribute("rel", "stylesheet");
				pplsCSS.setAttribute("type", "text/css");
				pplsCSS.setAttribute("href", ppls_cdn_url + "/css/internalStyle.css");
				headElem.insertBefore(pplsCSS,headElem.firstChild);
				var bsCSS=document.createElement('link');
     				bsCSS.setAttribute("rel", "stylesheet");
				bsCSS.setAttribute("type", "text/css");
				bsCSS.setAttribute("href", ppls_cdn_url + "/css/pplsay_bootstrap.min.css");
				headElem.insertBefore(bsCSS,headElem.firstChild);
  			      	var pplsJS=document.createElement('script');
			      	pplsJS.setAttribute("type","text/javascript");
			      	pplsJS.setAttribute("src", ppls_cdn_url+ "/js/default/conversationsRenderer.js");
			      	headElem.appendChild(pplsJS);
			
			</script>
		</div>
		<div id="PPLSAYLink" class="row" style="padding-left: 15px;">
			<a href="http://pplsay.com" onclick = "window.open(this.href, 'mywin','left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;">
				<span class="pplsay-label" style="font-weight: bold;font-size:13px;float: left">Powered by:</span>
				<img style="" src="<?php echo $this->getPPLSayCdnURL();?>/images/logoLink.png" style="border:0;" alt="PPLSAY - Connecting to Crowd Voice">
			</a> 
		</div>
	</div>


