<div style="width:inherit">
            <ul class="nav nav-tabs" id="myTabs" style="width:inherit">
		    <?php foreach ($this->getTabs() as $_index => $_tab): ?>
			<?php if($this->getChildHtml($_tab['alias'])): ?>
			    <li id="product_tabs_<?php echo $_tab['alias'] ?>" class="<?php echo !$_index?' active first':(($_index==count($this->getTabs())-1)?' last':'')?>"><a href="#product_tabs_<?php echo $_tab['alias'] ?>_contents" data-toggle="tab"><?php echo $_tab['title']?></a></li>
			<?php endif; ?>
		    <?php endforeach; ?>
		</ul>
            <div class="tab-content">

<?php foreach ($this->getTabs() as $_index => $_tab): ?>
    	<?php if($this->getChildHtml($_tab['alias']) and $_index==0): ?>
       		 <div class="tab-pane active" id="product_tabs_<?php echo $_tab['alias'] ?>_contents"><?php echo $this->getChildHtml($_tab['alias']) ?></div>
    <?php endif; ?>
    	<?php if($this->getChildHtml($_tab['alias']) and $_index!=0 ): ?>
       		 <div class="tab-pane" id="product_tabs_<?php echo $_tab['alias'] ?>_contents"><?php echo $this->getChildHtml($_tab['alias']) ?></div>
    <?php endif; ?>
<?php endforeach; ?>
	  </div>
</div>​

<script>
$j('#myTabs').bind('show', function(e) {  

    // identify the tab-pane
    paneID = $j(e.target).attr('href');

    // get the value of the custom data attribute to use as the iframe source
    src = $j(paneID).attr('data-src');

    //if the iframe on the selected tab-pane hasn't been loaded yet...
    if($j(paneID+" iframe").attr("src")=="")
    {
        // update the iframe src attribute using the custom data-attribute value
        $j(paneID+" iframe").attr("src",src);
    }
});
</script>

