<?php $this->getChild('virality')->initVirality($this->getChild('child')->getProduct()->getId())?>
<?php if ($this->getChild('virality')->count!=0): ?>
	<div class="ppls_virality" style="width:140px;height:20px;"> 
		
			<img style="width:70px;height:14px;" src="<?php echo $this->getChild('virality')->getLink() ?>"><span style="margin-left:5px">(<?php echo $this->getChild('virality')->count?>)</span>
	</div>
<?php endif; ?>
<?php echo $this->getChildHtml('child') ?>



